/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Department,
  Section,
  JobTitle,
  CostCenter,
  InsuranceConfig,
  InsuranceOffice,
  ResignationReason,
  VacationType,
  Employee,
  VacationRequest,
  AttendanceRecord,
  SystemMonth,
  UserPermission,
  SystemAlert,
} from '../types';

export const initialDepartments: Department[] = [
  { id: 'dept-1', name: 'الموارد البشرية' },
  { id: 'dept-2', name: 'الحسابات والمالية' },
  { id: 'dept-3', name: 'المبيعات والتسويق' },
  { id: 'dept-4', name: 'تكنولوجيا المعلومات' },
  { id: 'dept-5', name: 'التشغيل والصيانة' },
];

export const initialSections: Section[] = [
  { id: 'sec-1', name: 'شئون العاملين', departmentId: 'dept-1' },
  { id: 'sec-2', name: 'الاستقطابات والتعيينات', departmentId: 'dept-1' },
  { id: 'sec-3', name: 'الحسابات العامة', departmentId: 'dept-2' },
  { id: 'sec-4', name: 'الأجور والمرتبات', departmentId: 'dept-2' },
  { id: 'sec-5', name: 'المبيعات الخارجية', departmentId: 'dept-3' },
  { id: 'sec-6', name: 'الدعم الفني', departmentId: 'dept-4' },
];

export const initialJobTitles: JobTitle[] = [
  { id: 'job-1', name: 'مدير الموارد البشرية' },
  { id: 'job-2', name: 'أخصائي شئون عاملين' },
  { id: 'job-3', name: 'مدير حسابات' },
  { id: 'job-4', name: 'محاسب أجور' },
  { id: 'job-5', name: 'أخصائي تسويق' },
  { id: 'job-6', name: 'مهندس برمجيات' },
  { id: 'job-7', name: 'فني تشغيل' },
  { id: 'job-8', name: 'مشرف مبيعات' },
];

export const initialCostCenters: CostCenter[] = [
  { id: 'cc-1', code: '1001', name: 'الإدارة العامة - المركز الرئيسي' },
  { id: 'cc-2', code: '1002', name: 'فرع الجيزة والمستودعات' },
  { id: 'cc-3', code: '1003', name: 'مكتب الإسكندرية والساحل' },
];

export const initialInsuranceConfig: InsuranceConfig = {
  id: 'ins-config-default',
  employeeRatio: 11, // 11%
  companyRatio: 18.75, // 18.75%
  minLimit: 2000,
  maxLimit: 12600,
};

export const initialInsuranceOffices: InsuranceOffice[] = [
  { id: 'off-1', code: '210', name: 'مكتب تأمينات الدقي' },
  { id: 'off-2', code: '212', name: 'مكتب تأمينات مدينة نصر ثاني' },
  { id: 'off-3', code: '215', name: 'مكتب تأمينات مصر الجديدة' },
];

export const initialResignationReasons: ResignationReason[] = [
  { id: 'res-1', reason: 'تقديم استقالة بداعي السفر للخارج' },
  { id: 'res-2', reason: 'الحصول على فرصة عمل بديلة' },
  { id: 'res-3', reason: 'ظروف شخصية / عائلية' },
  { id: 'res-4', reason: 'التسوية بالاتفاق الودي' },
  { id: 'res-5', reason: 'بلوغ سن المعاش القانوني' },
];

export const initialVacationTypes: VacationType[] = [
  { id: 'vac-1', name: 'إجازة اعتيادية سنوية', daysAllowed: 21 },
  { id: 'vac-2', name: 'إجازة عارضة', daysAllowed: 7 },
  { id: 'vac-3', name: 'إجازة مرضية بأجر كامل', daysAllowed: 15 },
  { id: 'vac-4', name: 'إجازة بدون راتب', daysAllowed: 90 },
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    code: '101',
    name: 'أحمد محمود عبد الرحمن',
    nationalId: '29001150102456',
    phone: '01012345678',
    email: 'ahmed.m@company.com',
    departmentId: 'dept-1',
    sectionId: 'sec-1',
    jobId: 'job-1',
    costCenterId: 'cc-1',
    hireDate: '2020-03-15',
    status: 'active',
    insuranceNumber: '54891236',
    insuranceOfficeId: 'off-1',
    basicSalary: 15000,
    insuranceSalary: 8500,
    initialVacationBalance: 21,
    vacationBalance: 14,
    address: 'القاهرة، مصر الجديدة، شارع البرغوثي م١٢',
    socialStatus: 'متزوج ويعول',
    altPhone: '01122334455',
    nationalIdExpiry: '2029-05-14',
    insuranceStartDate: '2020-04-01',
    dateOfBirth: '1990-01-15',
    placeOfBirth: 'القاهرة',
    actualSalary: 17500,
    qualification: 'بكالوريوس هندسة حاسبات',
    qualificationIssuer: 'جامعة عين شمس',
    militaryStatus: 'أدى الخدمة العسكرية',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'مطور برمجيات أول',
    newJobDate: '2024-01-01',
    personalPhoto: '',
    gender: 'ذكر',
  },
  {
    id: 'emp-2',
    code: '102',
    name: 'سارة محمد حسن سلامة',
    nationalId: '29508020104856',
    phone: '01234567890',
    email: 'sara.h@company.com',
    departmentId: 'dept-1',
    sectionId: 'sec-1',
    jobId: 'job-2',
    costCenterId: 'cc-1',
    hireDate: '2022-06-01',
    status: 'active',
    insuranceNumber: '62145892',
    insuranceOfficeId: 'off-1',
    basicSalary: 8500,
    insuranceSalary: 6000,
    initialVacationBalance: 21,
    vacationBalance: 18,
    address: 'الجيزة، فيصل، شارع العشرين الرئيسي',
    socialStatus: 'آنسة',
    altPhone: '01055667788',
    nationalIdExpiry: '2030-08-01',
    insuranceStartDate: '2022-07-01',
    dateOfBirth: '1995-08-02',
    placeOfBirth: 'الجيزة',
    actualSalary: 9500,
    qualification: 'بكالوريوس نظم معلومات إدارية',
    qualificationIssuer: 'جامعة حلوان',
    militaryStatus: 'غير مطلوب للتجنيد',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'أخصائي شؤون العاملين',
    newJobDate: '2023-01-01',
    personalPhoto: '',
    gender: 'أنثى',
  },
  {
    id: 'emp-3',
    code: '103',
    name: 'عماد مصطفى كمال',
    nationalId: '28811120201478',
    phone: '01511223344',
    email: 'emad.m@company.com',
    departmentId: 'dept-2',
    sectionId: 'sec-4',
    jobId: 'job-4',
    costCenterId: 'cc-1',
    hireDate: '2021-01-10',
    status: 'active',
    insuranceNumber: '48951234',
    insuranceOfficeId: 'off-3',
    basicSalary: 9500,
    insuranceSalary: 7200,
    initialVacationBalance: 30,
    vacationBalance: 25,
    address: 'القليوبية، بنها، حي الزهور م٥',
    socialStatus: 'متزوج',
    altPhone: '01233445566',
    nationalIdExpiry: '2028-11-10',
    insuranceStartDate: '2021-02-01',
    dateOfBirth: '1888-11-12',
    placeOfBirth: 'القليوبية',
    actualSalary: 11000,
    qualification: 'بكالوريوس تجارة شعبة محاسبة',
    qualificationIssuer: 'جامعة بنها',
    militaryStatus: 'أدى الخدمة العسكرية',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'محاسب مالي أول',
    newJobDate: '2024-06-01',
    personalPhoto: '',
    gender: 'ذكر',
  },
  {
    id: 'emp-4',
    code: '104',
    name: 'تامر حسني عبد الكريم',
    nationalId: '29105200109574',
    phone: '01123459871',
    email: 'tamer.h@company.com',
    departmentId: 'dept-3',
    sectionId: 'sec-5',
    jobId: 'job-8',
    costCenterId: 'cc-2',
    hireDate: '2019-11-01',
    status: 'active',
    insuranceNumber: '89541247',
    insuranceOfficeId: 'off-2',
    basicSalary: 11000,
    insuranceSalary: 8200,
    initialVacationBalance: 21,
    vacationBalance: 11,
    address: 'القاهرة، حلوان، شارع شريف البحري',
    socialStatus: 'أعزب',
    altPhone: '01555667711',
    nationalIdExpiry: '2027-05-19',
    insuranceStartDate: '2019-12-01',
    dateOfBirth: '1991-05-20',
    placeOfBirth: 'القاهرة',
    actualSalary: 12500,
    qualification: 'بكالوريوس علوم حاسب',
    qualificationIssuer: 'جامعة القاهرة',
    militaryStatus: 'أدى الخدمة العسكرية',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'مهندس شبكات أول',
    newJobDate: '2022-10-01',
    personalPhoto: '',
    gender: 'ذكر',
  },
  {
    id: 'emp-5',
    code: '105',
    name: 'نجلاء فتحي علي زهران',
    nationalId: '29610140103598',
    phone: '01298765432',
    email: 'naglaa.f@company.com',
    departmentId: 'dept-4',
    sectionId: 'sec-6',
    jobId: 'job-6',
    costCenterId: 'cc-1',
    hireDate: '2023-01-15',
    status: 'active',
    insuranceNumber: '92147586',
    insuranceOfficeId: 'off-1',
    basicSalary: 13000,
    insuranceSalary: 9000,
    initialVacationBalance: 21,
    vacationBalance: 19,
    address: 'السادس من أكتوبر، الحي المتميز د٢',
    socialStatus: 'متزوجة',
    altPhone: '01124589632',
    nationalIdExpiry: '2031-10-12',
    insuranceStartDate: '2023-02-01',
    dateOfBirth: '1996-10-14',
    placeOfBirth: 'الجيزة',
    actualSalary: 15000,
    qualification: 'بكالوريوس صيدلة',
    qualificationIssuer: 'جامعة أكتوبر للعلوم والآداب',
    militaryStatus: 'غير مطلوب للتجنيد',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'مشرف جودة',
    newJobDate: '2025-01-01',
    personalPhoto: '',
    gender: 'أنثى',
  },
  {
    id: 'emp-6',
    code: '106',
    name: 'خالد مصطفى بكور',
    nationalId: '28204200102589',
    phone: '01045874125',
    email: 'khaled.b@company.com',
    departmentId: 'dept-5',
    sectionId: 'sec-1',
    jobId: 'job-7',
    costCenterId: 'cc-3',
    hireDate: '2018-02-10',
    status: 'terminated',
    terminationDate: '2026-05-30',
    terminationReasonId: 'res-2',
    insuranceNumber: '25489632',
    insuranceOfficeId: 'off-3',
    basicSalary: 7500,
    insuranceSalary: 5500,
    initialVacationBalance: 21,
    vacationBalance: 5,
    address: 'الإسكندرية، العجمي، شارع البيطاش العام',
    socialStatus: 'متزوج ويعول',
    altPhone: '01247859632',
    nationalIdExpiry: '2032-04-19',
    insuranceStartDate: '2018-03-01',
    dateOfBirth: '1982-04-20',
    placeOfBirth: 'الإسكندرية',
    actualSalary: 8500,
    qualification: 'دبلوم صنايع فني',
    qualificationIssuer: 'مديرية التربية والتعليم بالإسكندرية',
    militaryStatus: 'أدى الخدمة العسكرية',
    militaryDefermentExpiryDate: '',
    promotionTitle: 'مشرف حركة وسائق',
    newJobDate: '2020-05-01',
    personalPhoto: '',
    gender: 'ذكر',
  },
  {
    id: 'emp-7',
    code: '107',
    name: 'طارق علي محمود عبد الواحد',
    nationalId: '29912010103852',
    phone: '01147852369',
    email: 'tareq.a@company.com',
    departmentId: 'dept-2',
    sectionId: 'sec-3',
    jobId: 'job-3',
    costCenterId: 'cc-1',
    hireDate: '2026-04-01',
    status: 'active',
    insuranceNumber: '75489621',
    insuranceOfficeId: 'off-2',
    basicSalary: 14000,
    insuranceSalary: 10000,
    initialVacationBalance: 21,
    vacationBalance: 21,
    address: 'القاهرة، المعادي، شارع الـ ٩ الرئيسي',
    socialStatus: 'أعزب',
    altPhone: '01255887744',
    nationalIdExpiry: '2033-11-30',
    insuranceStartDate: '2026-04-01',
    dateOfBirth: '1999-12-01',
    placeOfBirth: 'المنوفية',
    actualSalary: 16000,
    qualification: 'ليسانس حقوق شعبة شريعة وقانون',
    qualificationIssuer: 'جامعة طنطا',
    militaryStatus: 'معافى مؤقت',
    militaryDefermentExpiryDate: '2028-04-01',
    promotionTitle: 'أخصائي قانوني',
    newJobDate: '2026-04-01',
    personalPhoto: '',
    gender: 'ذكر',
  }
];

export const initialVacationRequests: VacationRequest[] = [
  {
    id: 'req-1',
    employeeId: 'emp-1',
    vacationTypeId: 'vac-1',
    startDate: '2026-06-14',
    endDate: '2026-06-18',
    days: 5,
    status: 'approved',
    notes: 'إجازة سنوية لظروف عائلية وقضاء عطلة الصيف',
    requestDate: '2026-06-01',
  },
  {
    id: 'req-2',
    employeeId: 'emp-4',
    vacationTypeId: 'vac-2',
    startDate: '2026-06-07',
    endDate: '2026-06-07',
    days: 1,
    status: 'pending',
    notes: 'ظرف طارئ - عارضة',
    requestDate: '2026-06-07',
  },
  {
    id: 'req-3',
    employeeId: 'emp-3',
    vacationTypeId: 'vac-3',
    startDate: '2026-05-10',
    endDate: '2026-05-14',
    days: 5,
    status: 'approved',
    notes: 'وعكة صحية حادة بناء على تقرير طبي معتمد',
    requestDate: '2026-05-09',
  }
];

export const initialAttendanceRecords: AttendanceRecord[] = [
  // أحمد محمود (حاضر في الميعاد)
  { id: 'att-1', employeeId: 'emp-1', date: '2026-06-07', clockIn: '08:45', clockOut: '17:05', status: 'present' },
  // سارة محمد (متأخرة بضع دقائق)
  { id: 'att-2', employeeId: 'emp-2', date: '2026-06-07', clockIn: '09:15', clockOut: '17:00', status: 'late', notes: 'ازدحام مروري بالطريق الدائري' },
  // عماد مصطفى (حاضر ومبكر)
  { id: 'att-3', employeeId: 'emp-3', date: '2026-06-07', clockIn: '08:25', clockOut: '17:15', status: 'present' },
  // تامر حسني (إجازة معلقة - غياب بعذر مؤقتاً أو إجازة عارضة)
  { id: 'att-4', employeeId: 'emp-4', date: '2026-06-07', clockIn: '', clockOut: '', status: 'excused', notes: 'مقدم طلب إجازة عارضة لهذا اليوم' },
  // نجلاء فتحي (حاضرة)
  { id: 'att-5', employeeId: 'emp-5', date: '2026-06-07', clockIn: '08:50', clockOut: '17:00', status: 'present' },
  // طارق علي (غائب غير مبرر حتى الآن)
  { id: 'att-6', employeeId: 'emp-7', date: '2026-06-07', clockIn: '', clockOut: '', status: 'absent', notes: 'لم يتواصل مع الإدارة حتى الآن' },
];

export const initialSystemMonth: SystemMonth = {
  year: 2026,
  month: 6, // يونيو 2026
};

export const initialUserPermissions: UserPermission[] = [
  {
    id: 'user-admin',
    userCode: 'admin',
    userName: 'الأستاذ هاني معوض (المدير العام)',
    role: 'admin',
    permissions: {
      dataEntry: true,
      reports: true,
      controlPanel: true,
      settings: true,
    },
  },
  {
    id: 'user-entry',
    userCode: 'coder-1',
    userName: 'أخصائي إدخال بيانات',
    role: 'entry',
    permissions: {
      dataEntry: true,
      reports: false,
      controlPanel: false,
      settings: false,
    },
  },
  {
    id: 'user-manager',
    userCode: 'manager',
    userName: 'مدير الموارد البشرية الثاني',
    role: 'manager',
    permissions: {
      dataEntry: true,
      reports: true,
      controlPanel: true,
      settings: false,
    },
  }
];

export const initialAlerts: SystemAlert[] = [
  {
    id: 'alt-1',
    title: 'تأكيد تفعيل شهر النظام الجديد',
    description: 'تم ضبط شهر النظام الحالي بنجاح على شهر يونيو 2026. يرجى مراجعة كشوف الحضور والانصراف بانتظام.',
    date: '2026-06-01',
    type: 'success',
  },
  {
    id: 'alt-2',
    title: 'طلب إجازة معلق يتطلب مراجعة',
    description: 'الموظف "تامر حسني عبد الكريم" قدم طلب إجازة عارضة بتاريخ اليوم 2026-06-07 ومسجل كطلب معلق.',
    date: '2026-06-07',
    type: 'warning',
  },
  {
    id: 'alt-3',
    title: 'موظفين غير مسجلين بالتأمينات الاجتماعية',
    description: 'الموظف "سارة محمد حسن سلامة" بحاجة لتحديث ملف التأمينات والمكتب التأميني التابع لها لتجنب الغرامات.',
    date: '2026-06-05',
    type: 'info',
  }
];
